### ISSUE TITLE
subscribe git channel with Chart.yaml and values.yaml files

### ISSUE THREAD

**Issue by callum-stakater** [open-cluster-management-io/multicloud-operators-subscription#159]
If you create a git channel and subscribe to a path that contains a Chart.yaml and values.yaml I would except OCM to be able to deploy the chart similar to how ArgoCD is able too

It seems it is able to determine the Chart.yaml is a helm object and creates a HelmRelease but seems no resources are deployed

Example:

```
## I was hoping this one would work, to source Chart.yaml from git repo but it doesnt
## seem to work as expected, it does create the helmrelease but cant see why the resources
## dont get deployed

apiVersion: v1
kind: Namespace
metadata:
  name: nordmart-review
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nordmart-review
  namespace: nordmart-review
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nordmart-review
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: deploy/
    apps.open-cluster-management.io/reconcile-option: replace
  labels:
    app: nordmart-review
  name: nordmart-review-subscription-dev
  namespace: nordmart-review
spec:
  channel: rhacm-channel-stakater-lab-nordmart-review/rhacm-channel-stakater-lab-nordmart-review
  placement:
    placementRef:
      kind: PlacementRule
      name: nordmart-review-placement-dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: nordmart-review
  name: nordmart-review-placement-dev
  namespace: nordmart-review
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
 ---
 apiVersion: v1
kind: Namespace
metadata:
  name: rhacm-channel-stakater-lab-nordmart-review
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: rhacm-channel-stakater-lab-nordmart-review
  namespace: rhacm-channel-stakater-lab-nordmart-review
spec:
  type: Git
  pathname: 'https://github.com/stakater-lab/stakater-nordmart-review'
```     

All the content here is publicly available so should be possible to deploy this as is to recreate the issue

Struggling to find any thing relevant in docs or google foo which makes me think I am maybe doing something wrong?
