### ISSUE TITLE
Unable to override package attributes with python kubernetes.

### ISSUE THREAD

**Issue by aviweit** [open-cluster-management-io/multicloud-operators-subscription#29]
I am able to create a subscription based on a GitHub channel that overrides package parameters (its metadata.name) by creating the below yaml with `kubectl`.

```
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: core-wf
  name: my-5g-core-instance
  namespace: 5g-core
spec:
  channel: gitops-chn-ns/gitops
  placement:
    clusters:
    - name: cluster1
  packageOverrides:
  - packageName: fiveg-core
    packageOverrides:
    - path: metadata.name
      value: my-5g-core-instance
```

However when doing the same with python kubernetes library (kubernetes==10.0.1) using the below code:

```
        self.api = kubernetes.client.CustomObjectsApi()
        ...
        self.api.create_namespaced_custom_object(
            group='apps.open-cluster-management.io',
            version='v1',
            namespace=namespace,
            plural='subscriptions',
            body=subscription)
```

the package get propagated to the target cluster (e.g. cluster1) but without having its parameters to get overriden.

I verified that the subscription CR created by the python sdk code, properly contains packageOverrides and I wonder why doesn't it get overridden with the customized name that I pass it via `path: metadata.name`.

My environment consists of two clusters: both `v1.19.4` where open-cluster-management is installed via instructions: https://open-cluster-management.io/getting-started/quick-start/ which manages the other cluster I have.

Thanks.

**Comment by aviweit** [comment]
I am pasting the roles of my python pod. Thanks.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-proxy
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```
