### ISSUE TITLE
Unable to create Subscription CR from Argo workflow

### ISSUE THREAD

**Issue by aviweit** [open-cluster-management-io/multicloud-operators-subscription#32]
Hi,

I would like to be able to orchestrate Subscription creation from via Argo. 

I have three clusters in my environment:

1. open-cluster-management hub
2. 'paris-core' cluster
3. 'paris-2' cluster

I am following the example at https://github.com/open-cluster-management-io/multicloud-operators-subscription/tree/main/examples/remote-git-sub. I can successfully apply the yamls and notice nginx deployment.

However, when I create the subscription from via Hub cluster Argo (`argo submit ./wf.yaml -n 5g-core  --watch`), it does not work; the the nginx is properly deployed into paris-core but the subscription CR get **unexpectedly deleted** from the managed cluster.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example-from-argo-acm
spec:
  entrypoint: handlerequest
  arguments:
    parameters:
    - name: cluster_core
      value: paris-core

  templates:
  - name: handlerequest
    dag:
      tasks:
      - name: create-example-subscription
        template: create-example-subscription

  - name: create-example-subscription
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: apps.open-cluster-management.io/v1
        kind: Subscription
        metadata:
          annotations:
            apps.open-cluster-management.io/github-branch: main
            apps.open-cluster-management.io/github-path: examples/remote-git-sub-op
          name: {{workflow.name}}
        spec:
          channel: gitops-chn-ns/gitops
          placement:
            clusters:
            - name: {{workflow.parameters.cluster_core}}
```

How can I fix this issue?

Thanks in advance.
