### ISSUE TITLE
Cannot specify which resources to override in ClusterOverrides.

### ISSUE THREAD

**Issue by ivan-cai** [open-cluster-management-io/multicloud-operators-subscription#45]
I wonder why cannot specify which resources(apiversion,kind,name...) to override in ClusterOverrides(subscription.spec.overrides). Is is because the overrides only apply to the application dimension, not resource dimension？

**Comment by mikeshng** [comment]
Hi @ivan-cai ,
I think what you can use `PackageOverrides` + `Kustomize` see https://github.com/open-cluster-management-io/multicloud-operators-subscription/blob/main/docs/gitrepo_subscription.md#kustomize for Git app subscriptions 

For Helm subscriptions see https://github.com/open-cluster-management-io/multicloud-operators-subscription/blob/main/examples/helmrepo-channel/02-subscription.yaml#L10-L17 as an example to override chart values which can edit the resources.

As for `ClusterOverrides`, as the name implies it was meant to modify some desired clusters. For example,
```
  overrides:
  - clusterName: cluster2 # only do the follow Helm subscription package override for managed cluster name cluster2
    clusterOverrides:
    - path: spec.packageOverrides
      value:
      - packageName: apache
        packageOverrides:
        - path: spec
          value:
            replicaCount: 2
```
